blank_issues_enabled: true
contact_links:
  - name: Code of Conduct
    url: https://github.com/diegoandrade/PivotStream/blob/main/CODE_OF_CONDUCT.md
    about: Please review our community standards before posting.
